//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HostelApp
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class HotelBase2Entities : DbContext
    {
        private static HotelBase2Entities _context;
        public HotelBase2Entities()
            : base("name=HotelBase2Entities")
        {
        }

        public static HotelBase2Entities GetContext()
        {
            if (_context == null)
                _context = new HotelBase2Entities();
            return _context;
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<ЖалобыНаКомнату> ЖалобыНаКомнату { get; set; }
        public virtual DbSet<Жильцы> Жильцы { get; set; }
        public virtual DbSet<Комната> Комната { get; set; }
        public virtual DbSet<Общежитие> Общежитие { get; set; }
        public virtual DbSet<Тип> Тип { get; set; }
        public virtual DbSet<ФотоКомнаты> ФотоКомнаты { get; set; }
    }
}
