//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HostelApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class Комната
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Комната()
        {
            this.ЖалобыНаКомнату = new HashSet<ЖалобыНаКомнату>();
            this.ФотоКомнаты = new HashSet<ФотоКомнаты>();
            this.Общежитие = new HashSet<Общежитие>();
        }
    
        public int Код { get; set; }
        public int Номер { get; set; }
        public int СвободныеМеста { get; set; }
        public int КодЖильцы { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ЖалобыНаКомнату> ЖалобыНаКомнату { get; set; }
        public virtual Жильцы Жильцы { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ФотоКомнаты> ФотоКомнаты { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Общежитие> Общежитие { get; set; }
    }
}
