//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HostelApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class Общежитие
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Общежитие()
        {
            this.Комната = new HashSet<Комната>();
            this.Тип = new HashSet<Тип>();
        }
    
        public int Код { get; set; }
        public int КоличествоМест { get; set; }
        public string Название { get; set; }
        public string Описание { get; set; }
        public byte[] Фото { get; set; }
        public decimal Цена { get; set; }
        public bool Доступность { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Комната> Комната { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Тип> Тип { get; set; }
    }
}
